//import './jsxstudy/jsx-study1';
//import './jsxstudy/jsx-study2';
//import './component-basic/first-component';
//import './component-basic/props-basic';
//import './component-basic/props-children';
//import './component-basic/slotmachine';
//import './component-intermediate/state-study1';
//import './component-intermediate/UserProfile';
import './component-intermediate/state-study-with-inner-object';